cd ..
pytest --nbval 1-Introduction/1-Introduction.ipynb
pytest --nbval 1-Introduction/2-Notebook-Intro.ipynb
pytest --nbval "1-Introduction/Exploration-In-Geochemistry-(video).ipynb"
pytest --nbval 2-Reaction-Properties/1-Reaction-Properties.ipynb
pytest --nbval 2-Reaction-Properties/2-Activity-Diagrams.ipynb
pytest --nbval 2-Reaction-Properties/3-Animated-Diagrams.ipynb
pytest --nbval 2-Reaction-Properties/4-Univariant-Curves/1-Geothermometry.ipynb
pytest --nbval 2-Reaction-Properties/4-Univariant-Curves/2-Univariate-Curves-T-P.ipynb
pytest --nbval 3-Aqueous-Speciation/1-Introduction-to-Aq-Speciation/1-Intro-to-Aq-Speciation.ipynb
pytest --nbval 3-Aqueous-Speciation/1-Introduction-to-Aq-Speciation/2-Intro-to-Multi-Aq-Speciation.ipynb
pytest --nbval 3-Aqueous-Speciation/2-Multi-Sample-Speciation/Multi-Sample-Speciation.ipynb
pytest --nbval 3-Aqueous-Speciation/3-Charge-Balancing/Charge-Balancing.ipynb
pytest --nbval 3-Aqueous-Speciation/4-Custom-Database/1-Introduction/1-Introduction.ipynb
pytest --nbval 3-Aqueous-Speciation/4-Custom-Database/1-Introduction/2-Exercise.ipynb
pytest --nbval 3-Aqueous-Speciation/4-Custom-Database/Minimal-Example/Custom-Database.ipynb
pytest --nbval 3-Aqueous-Speciation/5-Alter-and-Suppress/Alter-and-Suppress.ipynb
pytest --nbval 3-Aqueous-Speciation/6-Extras/speciate-3i-file/speciate-3i-file.ipynb
pytest --nbval 3-Aqueous-Speciation/6-Extras/speciate-6i-file/speciate-6i-file.ipynb
pytest --nbval 4-Thermodynamic-Property-Estimation/Introduction-Aq-Organic-Estimator.ipynb
pytest --nbval 4-Thermodynamic-Property-Estimation/Aq-Organics-Feature-Demo/Aqueous-Organic-Molecules.ipynb
pytest --nbval WORKSHOP/WorkshopDemo.ipynb
pytest --nbval WORKSHOP/Breakout.ipynb